[package]
name = "codeite"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", version = "0.9", features = ["v4_10"] }
gio = "0.20"
glib = "0.20"
vte = { package = "vte4", version = "0.8" }
